package catalog

const InterfaceType Suffix = ".0"
const InterfaceName Suffix = ".1"
const LANBindAddress Suffix = ".2"
const LANBroadcastAddress Suffix = ".3"
const LANListenAddress Suffix = ".4"

const CardCreated Suffix = ".0.1"
const CardName Suffix = ".1"
const CardNumber Suffix = ".2"
const CardFrom Suffix = ".3"
const CardTo Suffix = ".4"
const CardGroups Suffix = ".5"

const GroupName Suffix = ".1"
const GroupCreated Suffix = ".0.1"

const DoorCreated = ".0.1"
const DoorControllerOID = ".0.2"
const DoorControllerCreated = ".0.2.1"
const DoorControllerName = ".0.2.2"
const DoorControllerID = ".0.2.3"
const DoorControllerDoor = ".0.2.4"
const DoorName = ".1"
const DoorDelay = ".2"
const DoorDelayStatus = ".2.1"
const DoorDelayConfigured = ".2.2"
const DoorDelayError = ".2.3"
const DoorControl = ".3"
const DoorControlStatus = ".3.1"
const DoorControlConfigured = ".3.2"
const DoorControlError = ".3.3"
