name: ghcr

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build:
    name: Push uhppoted-httpd container to ghcr.io
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.23
        cache: false

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Setup NPM
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install sass
      run: npm install -g sass

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install eslint
      run: npm install eslint eslint-config-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node --save-dev

    - name: Build Docker image
      run: |
        make docker-ghcr
        docker images

    - name: Docker login to ghcr.io
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push Docker 'latest' image to ghcr.io
      run: |
        docker push ghcr.io/uhppoted/httpd:latest

    - name: Push versioned Docker image to ghcr.io
      if: github.event_name == 'release' && github.event.action == 'published'
      run: |
        echo ">>>>>> build Docker image version ${{ github.event.release.tag_name }}"
        make docker-ghcr DOCKER=ghcr.io/uhppoted/httpd:0.8.8
        docker images
        docker push ghcr.io/uhppoted/httpd:0.8.8
