name: build

on:
  workflow_dispatch:
  push:
    branches: [ sass ]
  pull_request:
    branches: [ sass ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.24
        cache: false

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Setup NPM
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install eslint
      run: npm install eslint prettier --save-dev

    - name: Install sass
      run: npm install sass --save-dev

    - name: Build
      run: make build-all
